### ISSUE TITLE
Sonderzeichen in Suchanfrage

### ISSUE THREAD

**Issue by wolkoman** [ds-ultimate/ds-ultimatev2#4]
Der Spieler "Hustensaft Jüngling" in der DE Stämme Welt 170 kann nicht in der Suche gefunden werden.

Die Suchanfrage wurde über folgende URL aufgerufen:
https://ds-ultimate.de/search/de/player/Hustensaft%2BJ%C3%BCngling

Der Spieler ist in der Welt definitiv vorhanden:
https://de170.die-staemme.de/guest.php?name=Hustensaft+J%C3%BCngling

**Comment by wolkoman** [comment]
# Workaround
Manuelles Ersetzen des + durch %20 in der URL.
Beispielsweise ist der Aufruf via https://ds-ultimate.de/search/de/player/Hustensaft%20J%C3%BCngling erfolgreich.

**Comment by skatecram** [comment]
Vielen dank.
Haben das Problem gerade behoben im letzten commit.

https://github.com/extremeCrazyCoder/ds-ultimatev2/commit/625127cacf8f85e32e3912f4fe715fc3581b6822
