### ISSUE TITLE
Question on slowest unit

### ISSUE THREAD

**Issue by alex-d13** [ds-ultimate/ds-ultimatev2#6]
Hi, i have a question:

If I export my attack plan as DSWorkbench and import this text to a new Attack Plan, why is it that the slowest unit is always the speer unit? Is this feature missing or am I doing sth wrong?

Kindly,
Alex

**Comment by gbmd** [comment]
Same problem.

Sample attack planner: https://ds-ultimate.de/tools/attackPlanner/7265/edit/cRJe2PKRAE1GokhOkJ4BeL5XsIINQaLKIDlR9293
(single ram attack)

Export DSWorkbench: 16024&15275&&1588528800000&8&false&true&spear=MA==/sword=MA==/axe=MTAw/archer=MA==/spy=NTA=/light=MA==/marcher=MA==/heavy=MA==/ram=MQ==/catapult=MA==/knight=MA==/snob=MA==/militia=MA==

reimport of exported data converts attack to spear attack

**Comment by extremeCrazyCoder** [comment]
Can be a bug I'll check what goes wrong here in the evening

**Comment by skatecram** [comment]
> Hi, i have a question:
> 
> If I export my attack plan as DSWorkbench and import this text to a new Attack Plan, why is it that the slowest unit is always the speer unit? Is this feature missing or am I doing sth wrong?
> 
> Kindly,
> Alex

Hey @alex-d13 ,

Can you give us an example export?

**Comment by extremeCrazyCoder** [comment]
https://github.com/ds-ultimate/ds-ultimatev2/issues/6#issuecomment-623476563
did that already?
as you wrote me you already saw whats wrong
16024&15275 **&&** 1588528800000&8&false&true&spear=MA==/sword=MA==/axe=MTAw/archer=MA==/spy=NTA=/light=MA==/marcher=MA==/heavy=MA==/ram=MQ==/catapult=MA==/knight=MA==/snob=MA==/militia=MA==

**Comment by alex-d13** [comment]
26466&24006&&1588658400000&11&false&true&spear=MA==/sword=MA==/axe=MA==/archer=MA==/spy=MA==/light=MA==/marcher=MA==/heavy=MA==/ram=MA==/catapult=MA==/knight=MA==/snob=MA==/militia=MA==

for example was created as a ram-type unit and after importing this string it is displayed as speer-type unit

**Comment by gbmd** [comment]
Sample attack planner: https://ds-ultimate.de/tools/attackPlanner/7265/edit/cRJe2PKRAE1GokhOkJ4BeL5XsIINQaLKIDlR9293
(single ram attack)

contains an attack with a ram, as I would like to import. by exporting it **in ds ultimate** I get:  16024&15275&&1588528800000&8&false&true&spear=MA==/sword=MA==/axe=MTAw/archer=MA==/spy=NTA=/light=MA==/marcher=MA==/heavy=MA==/ram=MQ==/catapult=MA==/knight=MA==/snob=MA==/militia=MA==
which already contains the suspicious double-&

the export from ds workbench gives me a large XML-file quite unlike the condensed form that is required by ds ultimate. would you mind sending us your DSWorkbench export templates to check?

**Comment by extremeCrazyCoder** [comment]
we now fixed two issues
one with exporting and one with importing

it should work now

the xml export from workbench is currently not supported
the format that you see here is when you press STRG+C while selecting attack in the attack overview

**Comment by gbmd** [comment]
> we now fixed two issues
> one with exporting and one with importing
> 
> it should work now
> 
> the xml export from workbench is currently not supported
> the format that you see here is when you press STRG+C while selecting attack in the attack overview

Works great for me! Thanks! And it makes copying and pasting possible, which is a great feature itself.    // Oh thanks, alex-d13 already wrote a script to condense the xml down to the format. Guess theres an easier way now!

**Comment by extremeCrazyCoder** [comment]
could you link me this skript?
maybe we could also support xml format
