### ISSUE TITLE
Weltenmenü öffnet sich nicht (Mobile-Ansicht)

### ISSUE THREAD

**Issue by wolkoman** [ds-ultimate/ds-ultimatev2#7]
Versucht man in der Navigationsleiste mit der mobilen Ansicht das Weltenmenü zu öffnen (Menü > Welten > Normale Welten), so schließt sich das geöffnete Menü ohne eine weitere Auswahl zu bekommen.

![dsultimate](https://user-images.githubusercontent.com/8089982/80973854-32c39e80-8e20-11ea-878a-4df8b9f345c2.gif)

**Comment by wolkoman** [comment]
### Workaround

Auf den Menüeintrag klicken aber nicht loslassen. Mit der Maus den Menüeintrag verlassen und die Maus loslassen.

![dsultimate](https://user-images.githubusercontent.com/8089982/80974547-2a1f9800-8e21-11ea-85ff-9b9faf85cbad.gif)

**Comment by extremeCrazyCoder** [comment]
Soweit ich sehe liegt das daran, dass wir dasselbe menü für Desktop und mobile verwenden
Ich denke da muss man 2 unterschiedliche menüs machen

**Comment by extremeCrazyCoder** [comment]
Sollte erledigt sein mit 19554ab4564a9976e861eb595fb63239fe400b1c
